### ISSUE TITLE
Unsupported sql column, Postgres, int8range

### ISSUE THREAD

**Issue by sreuland** [go-jet/jet#101]
Hello, when trying jet(2.6.0) on a Postgres table that has column with a Postgres range type 'int8range', the jet generator emits some errors:

```[SQL Builder] Unsupported sql column '<column_name> int8range', using StringColumn instead.```

Is there a way to customize current generator to support this column type, or request to add this as new feature?

**Comment by go-jet** [comment]
Hi. Yeah, since the latest version it is possible. You can find more info in the [wiki page](https://github.com/go-jet/jet/wiki/Generator#generator-customization).

**Comment by sreuland** [comment]
ah, ok, nice, will try that out for PG's int8range, thanks!
