### ISSUE TITLE
[MySQL] Include column COMMENT into generated files

### ISSUE THREAD

**Issue by FlymeDllVa** [go-jet/jet#103]
Sign MySQL comments in Go struct

**Comment by go-jet** [comment]
Could you give more info?

**Comment by FlymeDllVa** [comment]
SQL `COMMENT 'TEXT'` => Go comment `// Type TEXT`

**Comment by go-jet** [comment]
Yeah, it makes sense.

**Comment by FlymeDllVa** [comment]
This also applies to the rest of the databases
Not only MySQL

**Comment by CmpHDL** [comment]
@go-jet Added to v2.8.0 milestone but v2.9.0 is released without, has this been added to the backlog?

**Comment by CmpHDL** [comment]
@go-jet ?

**Comment by go-jet** [comment]
Other, more prioritized features pushed this one out of previous releases, but I guess it can go with a the next release.

**Comment by go-jet** [comment]
Feature added in v2.10.0 release.
