### ISSUE TITLE
Is there a quick way to where in?

### ISSUE THREAD

**Issue by FlymeDllVa** [go-jet/jet#104]
``` go
SELECT(Actor.AllColumns).
FROM(Actor).
WHERE(
    ROW(Actor.FirstName).IN(
                ROW(String("Joe")),
                ROW(String("Nick")),
            ),
)
```

Is it possible to insert an array of strings at once? []string

**Comment by FlymeDllVa** [comment]
1. stmt = stmt.WHERE()
2. stmt = stmt.WHERE()

2 where rubs the first one, and does not put and between them. Is this normal? If so, how to live with it?

**Comment by go-jet** [comment]
1. 
```go
func StringExpressionList(values []string) []Expression {
  ....
}
...
 Actor.FirstName.IN(StringExpressionList(values)...) // there is no need to use ROW.
```

2. SQL doesn't support two WHERE clauses. You will have to use AND
```go
stmt.WHERE(cond1.AND(cond2))
```

In case you are trying to construct dynamic condition: https://github.com/go-jet/jet/wiki/FAQ#how-to-construct-dynamic-condition

**Comment by gmling** [comment]
> ```go
> func StringExpressionList(values []string) []Expression {
>   ....
> }
> ...
>  Actor.FirstName.IN(StringExpressionList(values)...) // there is no need to use ROW.
> ```
> 
> 2. SQL doesn't support two WHERE clauses. You will have to use AND
> 
> ```go
> stmt.WHERE(cond1.AND(cond2))
> ```
> 
> In case you are trying to construct dynamic condition: https://github.com/go-jet/jet/wiki/FAQ#how-to-construct-dynamic-condition

`StringExpressionList ` not support for now，will it support in the future？

**Comment by go-jet** [comment]
Yeah, I think we could include it as a helper method.
