### ISSUE TITLE
Update Docs Request

### ISSUE THREAD

**Issue by CmpHDL** [go-jet/jet#108]
Docs currently lack simple examples and extensive documentation.

For example:
How to preform an exists? (tests do not help at all, been trying for hours)
Normal SQL `SELECT EXISTS(SELECT 1 FROM users WHERE users.email = 'test@test.test');`
I just want a true or false to see if the record is there, I've tried every variation of with .EQ(Bool(true)) with .AS("exists") dest.exist, everything.
```
var dest struct {
    exists bool
}

stmt.Query(db, &dest)
```
I gave up and did a normal select into a model.Tables then did a 
```
if err != nil {
	if err == qrm.ErrNoRows {
		return false, nil
	}

	return false, err
}

return true, nil
```
Which is incredibly inefficient.

How to use .rows() a count on rows? grab the raw value instead of scan?

How to set normal types for the generator? (use template.NewType(type(seed value)) ie .NewType(int(11))
I write this ticket with much frustration with the amount of time I've spent trying to figure out incredibly basic things on something so promising and nothing seems to work and there are no simple examples.

**Comment by go-jet** [comment]
Hi.
1) There is nothing special about EXISTS function, you can find example [here](https://github.com/go-jet/jet/blob/d335b6cdad911055754999f00bc988efa0f57470/sqlite/select_statement_test.go#L136). The most likely reason why scan doesn't work is, because you're using private field as destination. The fix should be: `exists bool` => `Exists bool`, assuming statement is: `stmt:= SELECT(EXISTS(...).AS("exists"))`
2) To retrieve rows use [stmt.Rows(ctx, db)](https://github.com/go-jet/jet/blob/d335b6cdad911055754999f00bc988efa0f57470/tests/postgres/scan_test.go#L749).
3) Yep, `template.NewType(dummyObject)` is the way to specify a new type. `NewType` is using dummy object, and the value of the object is never checked(int(0), and int(11) are the same). It is not a seed value. [test](https://github.com/go-jet/jet/blob/d335b6cdad911055754999f00bc988efa0f57470/tests/postgres/generator_template_test.go#L316).
Alternatively you don't need to use NewType, you can specify type directly:
```go
field.Type = template.Type{
    ImportPath: "",
    Name: "int",
}
```

**Comment by CmpHDL** [comment]
> 

1. Thank you, I'll try this, wish it gave a an error "unable to access private field". Ironically most of the errors I'm getting are at runtime and I get almost no information on the error that happens when dumping err.
2. Documentation on its usages rather than just a test with its existence.
3. The dummy object itself needs a seeder, the examples in the test use types without dummy info and all use structs rather than a primitive type. Trying to use go/types results in a BasicType as the type. Specifying a raw type via the template.Type is simple yes and great, but not documented, to someone looking from the outside in, especially with import path, the type appears to be for internal use and only for custom types.

**Comment by CmpHDL** [comment]
> Hi.
> 
>     1. There is nothing special about EXISTS function, you can find example [here](https://github.com/go-jet/jet/blob/d335b6cdad911055754999f00bc988efa0f57470/sqlite/select_statement_test.go#L136). The most likely reason why scan doesn't work is, because you're using private field as destination. The fix should be: `exists bool` => `Exists bool`, assuming statement is: `stmt:= SELECT(EXISTS(...).AS("exists"))`
> 
>     2. To retrieve rows use [stmt.Rows(ctx, db)](https://github.com/go-jet/jet/blob/d335b6cdad911055754999f00bc988efa0f57470/tests/postgres/scan_test.go#L749).
> 
>     3. Yep, `template.NewType(dummyObject)` is the way to specify a new type. `NewType` is using dummy object, and the value of the object is never checked(int(0), and int(11) are the same). It is not a seed value. [test](https://github.com/go-jet/jet/blob/d335b6cdad911055754999f00bc988efa0f57470/tests/postgres/generator_template_test.go#L316).
>        Alternatively you don't need to use NewType, you can specify type directly:
> 
> 
> ```go
> field.Type = template.Type{
>     ImportPath: "",
>     Name: "int",
> }
> ```

1. Worked. However, try it yourself though with a lowercase exists, there is no compiletime / IDE error because its valid to access a private property there (realized now its getting passed as reference and then is inaccessible where its being dereferenced).

_**More importantly**, there is also no runtime error._ 
It just runs with no errors and returns a value of false every time, this 

1. Scares me a little
2. Is why its hard to debug / problem solve

**Comment by go-jet** [comment]
It is allowed to have a destination containing exported and unexplored fields, as well as exported fields without associated projections in the query. So in the situations like this scan would not return an error. Scan does not assume format of the destination, it will accepts any destination, and it will fill only exported fields that have corresponding projection in the query.
For more examples take a look at the `./tests/` folder.
And yes, documentation can always be improved. Feel free to contribute.
