### ISSUE TITLE
PostgreSQL views should be queriyable

### ISSUE THREAD

**Issue by khalidalkassoum** [go-jet/jet#11]
Hello,
excellent approach in the spirit of JOOQ (Java/Kotlin). Great project. Thank you.
Is there any specific reason why PostgreSQL "views" are excluded from SQL queries?

`SELECT table_name FROM information_schema.tables where table_schema = $1 
/* and table_type = 'BASE TABLE' */
;`

**Comment by go-jet** [comment]
Thanks @khalidalkassoum
Some of the features are left to be implemented in future releases.
This will be probably added in next 2.1.0 release, along with WINDOW functions.
If you lack some feature, feel free to open new issue, so that missing functionalities can be prioritized.

**Comment by go-jet** [comment]
@khalidalkassoum 
View support is now on the master branch. Please give it a try.
In next couple of days, after additional testing, it should be officially released as part of 2.1.0 version.

**Comment by khalidalkassoum** [comment]
@go-jet 
thank you very much for this preview. Nice peace of code.
I've been testing it since yesterday (go 1.3, postgreSql 11). No problem so far.

**Comment by go-jet** [comment]
View support is now part of the latest release v2.1.0.
Important note:
To use `view` model type as grouping destination primary_key tag has to be specified manually. More information [here](https://github.com/go-jet/jet/wiki/Query-Result-Mapping-(QRM)#specifying-primary-keys).
