### ISSUE TITLE
Scan into struct type

### ISSUE THREAD

**Issue by CmpHDL** [go-jet/jet#114]
**Describe the bug**
Scanning into custom struct from non-table appears to not work.

**Environment (please complete the following information):**
 - OS: macosx
 - Database: postgres
-  Database driver: sql.DB
 - Jet version 2.6.0 branch type-recursion

**Code snippet**

Scanning into this works.
```
var dest []struct {
    FieldName string
    FieldName2 string
}
```

Scanning into this does not work.
```
type ModelName struct {
    FieldName string
    FieldName2 string
}

var dest []ModelName
```

**Expected behavior**
Scanning into the struct version and model version should both work.

**Comment by CmpHDL** [comment]
```
type ModelName []struct {
    FieldName string
    FieldName2 string
}

var dest ModelName
```

For some reason this does work however.

**Comment by go-jet** [comment]
Since you've changed your destination from anonymous struct type to named struct type, you would need to update query aliases as well.
Assuming your query has:
```go
.AS("field_name")
.AS("filed_name2")
```
The fix would be:
```go
.AS("model_name.field_name")
.AS("model_name.filed_name2")
```
More info can be found [here](https://github.com/go-jet/jet/wiki/Query-Result-Mapping-(QRM)#custom-model-types).
