### ISSUE TITLE
Table prefix and suffix for multi-tenant environment

### ISSUE THREAD

**Issue by fourdim** [go-jet/jet#125]
**Feature needed**
Hi, there. I've read the wiki and learnt that the solution for jet to manage multi-tenant environment is to use the function:
```go
Artist2 := Artist.FromSchema("chinook2")
```
As MySQL treats `schema` the same as `database`, I would like to have a multi-tenant environment based on the prefix or suffix of tables.

**Suggested solution**
Modify the generator by adding the functions like:
```go
Artist2 := Artist.WithPrefix("chinook2")
Artist3 := Artist.WithSuffix("chinook2")
``` 

```go
func (a {{tableTemplate.TypeName}}) WithPrefix(prefix string) {{tableTemplate.TypeName}} {
	return new{{tableTemplate.TypeName}}(a.SchemaName(), prefix+a.TableName(), a.Alias())
}
```

Or simply export the function `new{{tableTemplate.TypeName}}`.

**Comment by go-jet** [comment]
Hi @fourdim. Yeah, it make sense to add `WithPrefix` and `WithSufix` methods. 

What's your plan in general? 
To have tables like `artist`, `tenat01.artist`, `tenant02.artist`, etc... 
Where `artist` table will be used just as a template for jet generation, and other tables would be ignored by jet generator.

If we change table name, we will also change default aliasing so `Artist.WithPrefix("tenat01.")` would expect `Tenant01Artist` model type as destination. So If we want destination to be generic `Artist` model type, we would need probably to set alias to `TableName()` inside `WithPrefix/Sufix` method. 

```golang
     return new{{tableTemplate.TypeName}}(a.SchemaName(), prefix+a.TableName(), a.TableName())
```

**Comment by fourdim** [comment]
> What's your plan in general?

My plan is to have `artist`, `tenat01_artist`, `tenant02_artist`, as the `.` may be treated as an operator in MySQL. Also, `artist` table would be the template, which was exactly what I was thinking.

> If we change table name, we will also change default aliasing so Artist.WithPrefix("tenat01.") would expect Tenant01Artist model type as destination. So If we want destination to be generic Artist model type, we would need probably to set alias to TableName() inside WithPrefix/Sufix method.

It seems that you are right. And I think this plan is good enough for me to solve the multi-tenant problem.

**Comment by go-jet** [comment]
Do you want to open a PR? Contributions are always welcomed.
