### ISSUE TITLE
add conditional statements IF-THEN-ELSE 

### ISSUE THREAD

**Issue by VladislavSharoshkin** [go-jet/jet#129]
IF parentid IS NULL OR parentid = ''
THEN
    RETURN fullname;
ELSE
    RETURN hp_true_filename(parentid) || '/' || fullname;
END IF;

**Comment by go-jet** [comment]
Hi @VladislavSharoshkin . You can use `CASE` operator instead:

```golang
CASE().
    WHEN(User.ParentID.IS_NULL()).THEN(User.FullName).
    ELSE(RawString("hp_true_filename(parentid)").CONCAT("/").CONCAT(User.FullName)),
```

`CREATE FUNCTION` and `RETURN` are currently not supported.

**Comment by VladislavSharoshkin** [comment]
hi @go-jet, thanks, your answer helped me
