### ISSUE TITLE
This library doesnt work with sql.Conn

### ISSUE THREAD

**Issue by masterkidan** [go-jet/jet#140]
**Describe the bug**

**Environment (please complete the following information):**
 - OS: all
 - Database: all
-  Database driver: N/A
 - Jet version v2.7.1

**Code snippet**
Query statement and model files of interest.

The library doesn't work with sql.Conn as mentioned in the Readme sections. The issue is that qrm.DB expects the driver to implement both methods with context and without context, however [sql.Conn](https://pkg.go.dev/database/sql#Conn) only implements QueryContext, ExecContext etc. 
This makes this library difficult to use with Connection Pooling
**Expected behavior**
Update qrm.DB interface to only require methods with Context, that should allow it to work with sql.DB and sql.Conn.

**Comment by go-jet** [comment]
Hi @masterkidan. I think we could create two new interfaces `Queryable`(for QueryContext) and `Executable`(for ExecContext), which would be passed as a parameter instead of `qrm.DB`. `qrm.DB` is already part of public API, so we can't remove methods from it. But we can mark it as deprecated.
