### ISSUE TITLE
How to select MIN/MAX date field?

### ISSUE THREAD

**Issue by nboughton** [go-jet/jet#15]
I have a table of records that has a date DATETIME field. I need to select the earliest date and the latest date. In raw SQL this would be 

```sql
SELECT MIN(date) AS first, MAX(date) AS last FROM table;
```

However with jet there are only min/max funcs for integers and floats and no apparent way to convert a date field to an integer (effectively render it as unix time). How can I do this with Jet?

**Comment by go-jet** [comment]
@nboughton Thanks for catching this issue.

This issue is fixed now on `develop` branch, and it will be released during this week as a new hotfix.
Two new methods are added (MIN/MAX) that excepts any expression type.
For example: `MIN(table.date)` or `MAX(table.date)`.
