### ISSUE TITLE
Support JSON tags

### ISSUE THREAD

**Issue by jaupe** [go-jet/jet#157]
**Is your feature request related to a problem? Please describe.**
The JSON we send back needs to be lower-case. We don't want to add it to the generated model structs because if we re-generate, then we will lose the tags.

**Describe the solution you'd like**
Ability to add JSON tags in a maintenance-free manner if we re-generate the schema

**Comment by go-jet** [comment]
Hi @jaupe. It is possible to add tags to model types using [generator customization](https://github.com/go-jet/jet/wiki/Generator#generator-customization). Check the [test sample](https://github.com/go-jet/jet/blob/f2e4b8551c48b97d0cd2d3deff47dc1b2aa2f04e/tests/postgres/generator_template_test.go#L274).
