### ISSUE TITLE
Add postgres JSON cast type

### ISSUE THREAD

**Issue by wexder** [go-jet/jet#160]
**Is your feature request related to a problem? Please describe.**
We are using a lot of `json` fields in our postgres database. And it's hard to do the UPSERT with `json` column type.
Currect solution I found is double casting the json string. 
```
  insertStm := table.INSERT(table.AllColumns).MODEL(table).
  ON_CONFLICT(table.SomeColumn).DO_UPDATE(
  postgres.SET(
    table.JsonColumn.SET(postgres.StringExp(postgres.CAST(postgres.String(*data)).AS("json"))),
    ),
```

**Describe the solution you'd like**
Add `postgres.Json()` func that would return `StringExpression`.

**Comment by wexder** [comment]
I've create PR for this https://github.com/go-jet/jet/pull/161

**Comment by go-jet** [comment]
Hi @wexder. Yeah, it makes sense to have a json literal.

**Comment by go-jet** [comment]
Support added with v2.9.0 release.
