### ISSUE TITLE
Unable to use `.IN` and `.NOT_IN` with dynamic values

### ISSUE THREAD

**Issue by philippta** [go-jet/jet#163]
**Describe the bug**
- `.IN(...)` and `.NOT_IN(...)` can not be used in conjuction with a slice of values (`Int`, `Float`, `String`, etc).
- The [`Expression` type](https://github.com/go-jet/jet/blob/master/internal/jet/expression.go#L5-L30) as well as `Int`, `Float`, `String`, etc. are living within the internal package, thus creating a slice of e.g. `jet.IntegerExpression` is not possible.

**Environment (please complete the following information):**
 - OS: macosx
 - Database: sqlite
-  Database driver: github.com/mattn/go-sqlite3
 - Jet version: 2.8.0

**Code snippet**
```go
import (
	. "myapp/table"

	"github.com/go-jet/jet/v2/internal/jet" // for jet.IntegerExpression, fails to compile
	. "github.com/go-jet/jet/v2/sqlite"
)

func demo() {
	var userIDs = []int64{1, 2, 3} // could be user provided
	var sqlIDs []jet.IntegerExpression

	for _, userID := range userIDs {
		sqlIDs = append(sqlIDs, Int(userID))
	}

	SELECT(Users.AllColumns).FROM(Users).WHERE(Users.UserID.IN(sqlIDs...))
}
```

Compilation error
```
use of internal package github.com/go-jet/jet/v2/internal/jet not allowed
```

**Expected behavior**
Defining a slice of `jet.IntegerExpression` should not result in a compilation error.

**Comment by go-jet** [comment]
Hi @philippta . All the internal types of interest are exported through dialect package([for instance](https://github.com/go-jet/jet/blob/master/sqlite/expressions.go)). There is no need to use internal package. In this case you should only import `github.com/go-jet/jet/v2/sqlite`.
`IN/NOT_IN` method does not accepts list of `IntegerExpression`, but list of `Expression` objects. This is a bug, but it can't be fixed before V3, because it is a part of the public API.

```golang
import (
	. "myapp/table"

	. "github.com/go-jet/jet/v2/sqlite"  // !!! Always import only the dialect package !!!
)

func demo() {
	var userIDs = []int64{1, 2, 3}         // could be user provided
	var sqlIDs []Expression                // !!! sqlite.Expression list !!! 

	for _, userID := range userIDs {
		sqlIDs = append(sqlIDs, Int(userID))
	}

	SELECT(Users.AllColumns).FROM(Users).WHERE(Users.UserID.IN(sqlIDs...))
}
```

**Comment by philippta** [comment]
Thanks for clarification. This definitely helps solving my problem. Maybe it‘s worth adding this example to the wiki.

Issue can be closed then.

**Comment by go-jet** [comment]
[wiki](https://github.com/go-jet/jet/wiki/FAQ#how-to-use-innot_in-with-dynamic-list-of-values)
