### ISSUE TITLE
Slice only contains one row

### ISSUE THREAD

**Issue by daddz** [go-jet/jet#177]
**Describe the bug**
While trying to figure out how to select and count in one query I stumbled upon a problem.

First some example code:
```
func ListFoo(db *sql.DB) ([]*model.Foo, int64, err) {
    stmt := SELECT(
        table.Foo.AllColumns,
        COUNT(STAR).AS("count")).
        FROM(table.Foo)

    var dest struct {
        Foo []*model.Foo
        Count int64
    }
    
    if err := stmt.Query(db, &dest); err != nil {
        return nil, 0, err
    }
    
    return dest.Foo, dest.Count, nil
}
```
Now `dest.Foo` only contains the first row/one element even though there are plenty more. 
The generated SQL is correct and returns all the rows.

**Environment (please complete the following information):**
 - OS: linux
 - Database: postgres
-  Database driver: pq
 - Jet version 2.8.0

**Expected behavior**
`dest.Foo` contains all selected rows that come back from the database.

**Comment by go-jet** [comment]
Hi @daddz. What are you trying to achieve with a query? On the first look query seems invalid, because `COUNT` requires group by column.

**Comment by daddz** [comment]
@go-jet oof, you're absolutely right - that doesn't make any sense. My thoughts must have taken a wrong turn and got stuck, thanks for clearing it up! :)
