### ISSUE TITLE
Scans using QueryContext override non-db properties.

### ISSUE THREAD

**Issue by CmpHDL** [go-jet/jet#204]
When using `stmt.QueryContext(context.Background(), tx, &eg)`,
properties on the Type that are not in the database are overridden with nils.

Example
```go
type User struct {
    model.Users
    Test string
}

main() {
    user := new(User)
    user.Test = "Test"

    fmt.Println(user.Test) // Prints "Test"

    stmt := table.Users.Insert()
    err := stmt.QueryContext(context.Background(), tx, &user)
    if err != nil { ... }

    fmt.Println(user.Test) // Prints ""
}
```

This applies to both public and private methods on the example type User.

**Comment by go-jet** [comment]
Hi @CmpHDL,

The object passed to the `QueryContext` method is used more as a template for the result object than as a destination for the result. Every time the `QueryContext` method is called, a new object is created, scanned into, and then this new object is assigned into provided object.

To preserve the value of `Test` field, you can scan directly into `Users` nested struct:

```golang
err := stmt.QueryContext(context.Background(), tx, &user.Users)
```

**Comment by CmpHDL** [comment]
Thank you @go-jet !
