### ISSUE TITLE
CGO Free SQLite Driver

### ISSUE THREAD

**Issue by zakaria-chahboun** [go-jet/jet#206]
First of all thanks for this amazing project 🌻

If you can add a support for https://gitlab.com/cznic/sqlite, It's a new CGO Free Sqlite driver.

**Comment by go-jet** [comment]
Hi @zakaria-chahboun,

Jet is independent of the sql driver. When creating db connections you can provide any driver of your choosing.
Currently, jet tests are run with `github.com/mattn/go-sqlite3`. I've tried to run them with `gitlab.com/cznic/sqlite` and a couple of tests failed. Mainly those working with `TIME`.  For instance:

```golang
stmt := SELECT(
    TIME(time.Now()).AS("time_now")
)

var dest struct {
     TimeNow time.Time
}

err := stmt.Query(db, &dest)

!!! dest.Time.IsZero
```

It is probably a driver issue, I'll double-check when I have more time.

**Comment by zakaria-chahboun** [comment]
@go-jet 
it's worked fine with me!
https://github.com/zakaria-chahboun/golang-sqlite-jet

**Comment by go-jet** [comment]
There are still some issues how time values are handled with this driver. I've opened the [merge request](https://gitlab.com/cznic/sqlite/-/merge_requests/51), with potential fix. I believe you can avoid the most of those issues by specifying `_time_format=sqlite` in connection string.
