### ISSUE TITLE
How can I change the generated package name "model" to "entity"?

### ISSUE THREAD

**Issue by 0radek** [go-jet/jet#208]
Just curious if its possible. Thank you

**Comment by go-jet** [comment]
Hi @0radek ,
Yes, it is possible. Check [generator customization](https://github.com/go-jet/jet/wiki/Generator#generator-customization) and test [example](https://github.com/go-jet/jet/blob/f2e4b8551c48b97d0cd2d3deff47dc1b2aa2f04e/tests/postgres/generator_template_test.go#L94).
