### ISSUE TITLE
How to customise mutableColumns to read-only generated columns in PostgreSQL?

### ISSUE THREAD

**Issue by rangzen** [go-jet/jet#209]
Hello,
We use generated columns with PostgreSQL, see [Generated Columns](https://www.postgresql.org/docs/15/ddl-generated-columns.html).
We would like to exclude these columns from the generated mutableColumns list.
Can we use something like [Generator customization](https://github.com/go-jet/jet/wiki/Generator#generator-customization)?
Is this possible without adding fields to `metadata.Table` or `metadata.Column`? Without changing `DefaultTableModel(tableMetaData metadata.Table) TableModel` to an interface to reimplement `(t table) MutableColumns() []Column`?
Thank you!

**Comment by go-jet** [comment]
Hi @rangzen,

Currently it is not possible to exclude columns from `AllColumns` or `MutableColumns` lists.
Workaround is to create new `ColumnList`s and use those instead. For instance:

```golang
var PeopleAllColumns     = People.AllColumns.Except(People.HeightIn)
var PeopleMutableColumns = People.MutableColumns.Except(People.HeightIn)
```

In terms of implementation, I suppose adding a new `Skip' flag would be enough to signal that the column should not appear in table sql builder struct.

**Comment by mlaflamm** [comment]
I just want to clarify that Postgres generated columns are read only. The goal would be to keep them in `AllColumns` and the table struct but to exclude them from `MutableColumns`.

**Comment by go-jet** [comment]
Aha, I see. In that case implementation can be simplified. We can retrieve additional column `is_generated` from `information_schema.columns` and then in `MutableColumns() []Column` filter out primary key and generated columns.

The only concern is this might affect existing users. But I think it should be fine, because generated columns can't be used in either insert or update statements, so existing users are probably already excluding generated columns.

**Comment by rangzen** [comment]
@go-jet PR and data pushed. Not sure how you deal with the submodule.

**Comment by rangzen** [comment]
Yep, CircleCI need first the link to the data submodule
`panic: open ./testdata/init/cockroach/test_generated.sql: no such file or directory`

**Comment by go-jet** [comment]
Yeah, when `jet-test-data` PR is merged, `jet` PR build will be fixed. For local development you can use makefile command - `make checkout-testdata`, in tests directory, to pull latest submodule master commit.
