### ISSUE TITLE
Expose the qrm function to convert sql.Row/Rows to Struct directly

### ISSUE THREAD

**Issue by duchiporexia** [go-jet/jet#21]
When I execute sql queries with external go sql library like 'sql/sqlx', not using jet's. I can get the sql.Result or sql.Row or sql.Rows. Then, how can I  convert them to Struct?

**Comment by duchiporexia** [comment]
@go-jet I have changed my comment. I mean when I get sql.Row or sql.Rows, how can I convert them to Struct?

**Comment by go-jet** [comment]
Jet doesn't have such a function. 
```go
Query(db DB, destination interface{}) error
```
Not that db can be of any type that implements this [interface](https://github.com/go-jet/jet/blob/master/qrm/db.go).
This includes: `sql.DB`, `sql.Tx` as well as  `sqlx.DB`, `sqlx.Tx`, `gorm.DB`, `gorm.Tx`, ....
So you don't need to execute query on 3rd party library and then map Rows into struct you just need to pass that 3rd party db/tx as a first argument of `Query`. 

If you are building query manually there is global function in qrm package:
```go
func Query(ctx context.Context, db DB, query string, args []interface{}, destPtr interface{}) error
```
