### ISSUE TITLE
less number of rows in result set than expected

### ISSUE THREAD

**Issue by msonawane** [go-jet/jet#217]
**Describe the bug**
Debug log show rows processed: 12
array of results shows only two rows scanned (length = 2)
running generated sql directly on database shows 12 rows results. Seems to be problem in scanning

Any way to debug how scan works ?

**Environment (please complete the following information):**
 - OS: linux
 - Database: postgres
 -  Database driver: pgx
 - Jet version [2.9.0]

**Expected behavior**

result set should have 12 rows

**Comment by go-jet** [comment]
If destination is array of complex structs, array length can be less then the number of rows processed.
Could you share your query and destination?

**Comment by go-jet** [comment]
@msonawane ?
