### ISSUE TITLE
Table alias is not reflected on fields

### ISSUE THREAD

**Issue by RangelReale** [go-jet/jet#222]
**Describe the bug**
When setting a table alias, the alias is not used on the fields and conditions, which returns errors, at least in postgres.

**Environment (please complete the following information):**
 - OS: windows
 - Database:  postgres
-  Database driver: pq
 - Jet version 2.9.0

**Code snippet**

```go
  SELECT(t.Device.DeviceID, t.Device.CompanyID, t.Device.DeviceName, COUNT(STAR).OVER()).
  FROM(t.Device.AS("d"))
```

```sql
SELECT device.device_id AS "device.device_id",
     device.company_id AS "device.company_id",
     device.device_name AS "device.device_name",
     COUNT(*) OVER ()
FROM public.device AS d;
```

```
failed to query db. error: pq: invalid reference to FROM-clause entry for table "device"
```

**Expected behavior**
The table alias should be used on all references to it.

**Comment by go-jet** [comment]
Hi, @RangelReale ,
You need to alias table before the query.

```golang

Device := t.Device.AS("d")
 
SELECT(Device.DeviceID, Device.CompanyID, Device.DeviceName, COUNT(STAR).OVER()).
FROM(Device)
```
