### ISSUE TITLE
Add an option to generate sample instant based on the current db value.

### ISSUE THREAD

**Issue by LintaoAmons** [go-jet/jet#225]
**Describe the solution you'd like**
I want use this to generate testing data, which there's already data can be use as a basement and I want to have an instance and I just need to change few fields to make an ideal data I want.

**Comment by go-jet** [comment]
Hi @LintaoAmons ,
I'm not sure what you mean. Could you give more info?

**Comment by LintaoAmons** [comment]
For example:

When `jet` generated the model type

```
type Aaaa struct {
	Id        *string 
	Mark      *bool 
	StartTime *time.Time
}
```

Maybe one way to achieve this is to also have a field tag `default` as default value.

The default values are randomly pick from one row that already existing in the database.

So can be easily used as a template. Cause most of the value are sensible to use the default value, just want to change one or two columns to build a new row.

My idea is demostrated as follow~
```
// generated by GPT
import (
	"reflect"
	"time"
)

type Aaaa struct {
	Id        *string `default:"234"`
	Mark      *bool   `default:"true"`
	StartTime *time.Time `default:"2023-03-28 01:00:00.000000 +00:00"`
}

func New(input interface{}) interface{} {
    // create a new instance of the input struct
    val := reflect.ValueOf(input).Elem()
    typ := val.Type()
    newStruct := reflect.New(typ).Elem()

    // loop through each field in the struct
    for i := 0; i < val.NumField(); i++ {
        field := val.Field(i)
        tag := typ.Field(i).Tag

        // check if the field has a default tag
        defaultVal, ok := tag.Lookup("default")
        if !ok {
            // if there's no default tag, use the existing value
            newStruct.Field(i).Set(field)
            continue
        }

        // set the default value based on the field type
        switch field.Type().String() {
        case "*string":
            newStruct.Field(i).Set(reflect.ValueOf(&defaultVal))
        case "*bool":
            boolVal, _ := strconv.ParseBool(defaultVal)
            newStruct.Field(i).Set(reflect.ValueOf(&boolVal))
        case "*time.Time":
            timeVal, _ := time.Parse(time.RFC3339, defaultVal)
            newStruct.Field(i).Set(reflect.ValueOf(&timeVal))
        }
    }

    return newStruct.Interface()
}
```

**Comment by LintaoAmons** [comment]
Or maybe my init idea is too much... maybe just generate one `sample_model` package

```go
.gen
└── postgres
    ├── table
        ├── model
        ├── **sample_model**
        ├── table
        └── view

model:
type Aaaa struct {
	Id        *string 
	Mark      *bool 
	StartTime *time.Time
}

sample_model:
var Aaaa = model.Aaaa{
	Id        "id"             // those values are comming from the db
	Mark      true 
	StartTime time...
}
```

**Comment by go-jet** [comment]
Aha, I see. I'm not sure about adding such a functionality to jet. 
There are already libraries providing such a functionality. For instance, quick search gave me this library: https://github.com/brianvoe/gofakeit
To initialize struct with a random data:
```golang
var foo model.Foo
gofakeit.Struct(&foo)
```
There is also option to customize random data, which you can use to read random db value.

**Comment by LintaoAmons** [comment]
Ok... Because it comes with more sensible data, so it somewhat have its value.

Yeah, thanks for your project, it's really nice.
