### ISSUE TITLE
VALUES clause support

### ISSUE THREAD

**Issue by v-byte-cpu** [go-jet/jet#233]
**Is your feature request related to a problem? Please describe.**

Hi there! It looks like Jet doesn't support [VALUES clause](https://www.postgresql.org/docs/current/sql-values.html). My personal use case is batch update statements, for instance

```
UPDATE public.some_table
SET name = (d.v)::text
FROM (
         VALUES (1, 'name1'), (2, 'name2')
     ) AS d(id, v)
WHERE some_table.id = (d.id)::bigint;
```
or 

```
WITH d(id, v) AS (VALUES (1, 'name1'), (2, 'name2'))
UPDATE public.some_table
SET name = (d.v)::text
FROM d where some_table.id = (d.id)::bigint;
```

**Describe the solution you'd like**

Public API support for VALUES clause.

**Comment by go-jet** [comment]
Hi @v-byte-cpu. `VALUES` is not supported currently. You can use this [workaround](https://github.com/go-jet/jet/issues/69#issuecomment-761809025) for now.

**Comment by go-jet** [comment]
`VALUES` Statements Support add in release v.2.12.0 ([wiki](https://github.com/go-jet/jet/wiki/VALUES))
