### ISSUE TITLE
How can I compare Postgres tuples?

### ISSUE THREAD

**Issue by BranislavLazic** [go-jet/jet#248]
I have a query like this:
```
SELECT * FROM table WHERE (x, y) < (0, 0);
```

How can I write the `WHERE` clause with Jet?
`WHERE x < 0 AND y < 0` is not the same.

Obviously `(x, y)` should be grouped into a `BoolExpression` and `(0, 0)` too.

**Comment by go-jet** [comment]
Hi @BranislavLazic ,

You can use `ROW` constructor to create a tuple, but unfortunately `Row` expression doesn't support comparison at the moment.

There are two workarounds for now:
1) Use [SQL Builder Cast Wrapper](https://github.com/go-jet/jet/wiki/Expressions#sql-builder-cast-wrapper) to cast into Int or Float expression.
```golang
IntExp(ROW(Table.X, Table.Y)).LT(IntExp(ROW(Int(1), Int(2)))) 
// IntExp would not add a cast into SQL query
```

2) Use [Raw expression](https://github.com/go-jet/jet/wiki/Expressions#raw-expression)
```golang
RawBool("(x, y) < (#1, #2)", RawArgs{"#1":10, "#2": 20})
```

**Comment by BranislavLazic** [comment]
@go-jet Thanks a lot! The first option looks suitable.
