### ISSUE TITLE
Control a destination of generator/postgres.GenerateDSN

### ISSUE THREAD

**Issue by kazhuravlev** [go-jet/jet#258]
**Problem**
We would like to control the destination directory of `postgres.GenerateDSN`, but inside this function we have a hardcoded value - the database name and schema path.

**Desired solution**
I see several options:
- Add option to `GenerateDSN` (backward compatibility issue)
- Create a new `GenerateDSN` with functional options for this and other changes (as in [Dave Cheney's article](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)). I can recommend [this tool](https://github.com/kazhuravlev/options-gen)
- Export `generator/postgres.postgresQuerySet` as `DefaultQuerySet() metadata.DialectQuerySet`

For our case, we would like to have the second option, hiding the complexity of the generator implementation.

**Comment by go-jet** [comment]
Hi @kazhuravlev.
It is possible to change destination directories using  [Generator Customization](https://github.com/go-jet/jet/wiki/Generator#generator-customization), check these tests for more details: [TestGeneratorTemplate_Schema_ChangePath](https://github.com/go-jet/jet/blob/f2e4b8551c48b97d0cd2d3deff47dc1b2aa2f04e/tests/postgres/generator_template_test.go#L38), [TestGeneratorTemplate_Model_ChangePath](https://github.com/go-jet/jet/blob/f2e4b8551c48b97d0cd2d3deff47dc1b2aa2f04e/tests/postgres/generator_template_test.go#L94) and [TestGeneratorTemplate_SQLBuilder_ChangePath](https://github.com/go-jet/jet/blob/f2e4b8551c48b97d0cd2d3deff47dc1b2aa2f04e/tests/postgres/generator_template_test.go#L112).

**Comment by kazhuravlev** [comment]
Of course I can manage the base directory. But I can't manage the rest of the directories (after the specified one).

When I set the resulting directory like `./output`, I get a result like `./output/<DBNAME>/<SCHEMA_NAME>`. But in my case there are multiple databases with different schemas inside each. So I don't want to have additional directories after `./output` . Only `./output/[model|table]` (instead of `./output/some__database_name/some__schema_name/[model|table] `).

Initial problem - I have local databases (dev dbs) and multiple databases in production. Each database is a separate tenant (client) with the same schema but different data. After generating, I get a little strange code, which contains the name of the database.

Main argument: The database name is only a configuration option and must be controlled by the jet user. Ideally, the schema name is the same.

**Comment by go-jet** [comment]
To remove database name, you can use relative path `"../"`.
```golang
err := postgres.Generate( // or GenerateDSN
	"./output",
	dbConnection,
	template.Default(postgres2.Dialect).
		UseSchema(func(schemaMetaData metadata.Schema) template.Schema {
			return template.DefaultSchema(schemaMetaData).UsePath("../")
		}),
)
```
Now generator will generate to `./output/[model|table|enum]` folders.

**Comment by kazhuravlev** [comment]
Thanks, solved!
