### ISSUE TITLE
Changing default alias

### ISSUE THREAD

**Issue by wijayaerick** [go-jet/jet#26]
I'm planning to use jet for query builder then I can map query results to my own Struct. Currently, jet generates alias with `table.column` format. For example:

```go
stmt := SELECT(Clients.AllColumns).FROM(Clients).WHERE(expression)
fmt.Println(stmt.DebugSql())
```
will prints
```sql
SELECT clients.id AS "clients.id",
     clients.created_at AS "clients.created_at",
     clients.updated_at AS "clients.updated_at",
     clients.username AS "clients.username"
FROM mydb.clients
WHERE clients.id = '12345';
```

However, I defined my struct like this:
```go
type Client struct {
	ID        uuid.UUID `db:"id"` // tag name is different with generated alias
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
	Username  string    `db:"username"`
}
```

This, of course, will cause error when I try to map the result. I could do either:
1. Use the jet generated model Struct instead of my own Struct
2. Change the tags to include table name (for example change `db:"id"` to `db:"clients.id"`), or
3. Change query statement to this:
```go
stmt := SELECT(
    Clients.ID.AS(Clients.ID.Name()),
    Clients.CreatedAt.AS(Clients.CreatedAt.Name()),
    Clients.UpdatedAt.AS(Clients.UpdatedAt.Name()),
    Clients.Username.AS(Clients.Username.Name())).
FROM(Clients).WHERE(expression)
```

I might go with the second solution, however it would be nicer if we have some way to control the default alias :wink:

https://github.com/go-jet/jet/blob/940fc06d9a2e2f146cd5b67f05dc96bb26253676/internal/jet/column.go#L58-L64

**Comment by go-jet** [comment]
@wijayaerick You can use standard table sql aliasing. For instance:
`client := Clients.AS("client")`
and then use aliased table instead `Clients`:
`stmt := SELECT(client.AllColumns).FROM(client)`

Or as you can tag the fields. But you should use `alias` tag instead of `db`. 
Sample usage can be seen here: https://github.com/go-jet/jet/wiki/Query-Result-Mapping-(QRM)#tagging-model-files

For example:
```go
type Client struct {
	ID        uuid.UUID `alias:"clients.id"` 
	CreatedAt time.Time `alias:"clients.created_at"`
	UpdatedAt time.Time `alias:"clients.updated_at"`
	Username  string    `alias:"clients.username"`
}
```    

Future version will add support for customizing generated model files(like names and types).
Is the additional 's' in the name, the only reason why you didn't want to use generated model files?

**Comment by wijayaerick** [comment]
@go-jet Thank you for the suggestion. Using empty alias does the trick; it removes the table name prefix in columns and still preserve table name in FROM statement. 

The reason I'm using my own model Struct is because I have methods defined in my models, for example func NewModel(..) *Model, func (m *Model) IsSomething() bool, etc..

**Comment by go-jet** [comment]
@wijayaerick If that's the case you can embed generated model struct into your custom model struct. For instance:
```go
packge mymodel

import ".../model"

struct Client struct {
   model.Clients
}

func (c Client) isSomething() bool {
   return c.Username != ""
}
```

With this approach you don't need to change SQL query for scan to work.

**Comment by wijayaerick** [comment]
Haven't thought about using embedding. Yes, that should work well for me. Thank you for your help. Also this is a great project and I'm looking forward to future development of this project.
