### ISSUE TITLE
It would be nice to allow internal types for building based on user input

### ISSUE THREAD

**Issue by albulescu** [go-jet/jet#270]
```
func buildWhereExpression(q any) jet.BoolExpression {}
```

**Comment by houten11** [comment]
Is [How to construct dynamic condition?](https://github.com/go-jet/jet/wiki/FAQ#how-to-construct-dynamic-condition) what you are looking for?

**Comment by albulescu** [comment]
Cool,  has support for `a.props->>'rooms' = '5'` clause too?

**Comment by houten11** [comment]
No, but you can use [Raw Expressions](https://github.com/go-jet/jet/wiki/Expressions#raw-expression) instead:

```golang
RawBool("t.props->>'key' = 'value'") 
// or
RawBool("t.props->> $k = $v", RawArg{"$k":"key", "$v": "value"}) 
```
