### ISSUE TITLE
Inject "AS OF SYSTEM TIME" into FROM clause

### ISSUE THREAD

**Issue by jetaggart** [go-jet/jet#280]
I'm using cockroachdb time travel queries and wondering if it's possible to inject "AS OF SYSTEM TIME" into the from clause as described here without resorting to raw sql: https://www.cockroachlabs.com/docs/stable/as-of-system-time

**Comment by houten11** [comment]
Hmm, I think it is not possible. You'll have to use raw SQL.

**Comment by jetaggart** [comment]
I ended up combining squirrel with this to get the generated names from jet and build this dynamically.
