### ISSUE TITLE
character varying = typeid error: Recipe `jet` failed on line 52 with exit code 1

### ISSUE THREAD

**Issue by spa5k** [go-jet/jet#284]
**Describe the bug**
It's giving error while generating the types

```
Connecting to postgres database...
Retrieving schema information...
Error trace:
 - failed to get 'public' schema metadata:
 - failed to get public tables metadata:
 - failed to query BASE TABLE metadata:
 - jet:
 - pq:
 - operator is only a shell:
 - character varying = typeid
error: Recipe `jet` failed on line 52 with exit code 1
```
**Environment (please complete the following information):**
 - OS: windows
 - Database: postgres
-  Database driver: no
 - Jet version v2.10.1

**Code snippet**
```sql

CREATE TABLE public.application_user (
    id public.application_user_id DEFAULT public.typeid_generate('application_user'::text) NOT NULL,
    customer_id public.customer_id NOT NULL,
    access_failed_count integer DEFAULT 0 NOT NULL,
    email text NOT NULL,
    email_confirmed boolean DEFAULT false NOT NULL,
    lockout_enabled boolean DEFAULT false NOT NULL,
    lockout_end timestamp with time zone,
    normalized_email text NOT NULL,
    normalized_user_name text NOT NULL,
    password_hash text NOT NULL,
    phone_number text,
    phone_number_confirmed boolean DEFAULT false NOT NULL,
    user_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);
```
https://github.com/jetpack-io/typeid

Using this as the primary key
**Expected behavior**
It should translate the typeid to `text`

**Comment by go-jet** [comment]
Hi @spa5k,
I'm having a problem to reproduce the bug. Generator successfully generates code for `application_user` table. Could you share how `application_user_id` and `customer_id` is defined.
Error trace points to operator error. It seems you are trying to compare `typeid` and `varchar`, which is not allowed.

**Comment by spa5k** [comment]
Hey I was able to fix it up, so basically in this file - https://github.com/jetpack-io/typeid-sql/blob/main/sql/03_typeid.sql, they were using VARCHAR and sometimes with fixed length of 63, I basically replaced it with text and it worked.
