### ISSUE TITLE
Postgres Materialized Views not generated

### ISSUE THREAD

**Issue by desol** [go-jet/jet#286]
**Is your feature request related to a problem? Please describe.**
I utilized materialized views for a project, and noticed Jet does not generate access to it via query building, and I will have to figure out a way to utilize raw SQL within my queries.

**Describe the solution you'd like**
Similar to how views are being generated, it would be nice to be able to query materialized views as well.

**Comment by go-jet** [comment]
Postgres materialized views support added in [Release v2.11.0](https://github.com/go-jet/jet/releases/tag/v2.11.0).
