### ISSUE TITLE
AS alias and ORDER_BY

### ISSUE THREAD

**Issue by ferllings** [go-jet/jet#308]
Hello,

Using mysql, I'm trying to get list of users first letter:

```
	stmt := SELECT(
		LEFT(User.name, Int(1)).AS("letter"),
	).DISTINCT().FROM(
		User,
	).ORDER_BY(
		String("letter").ASC(),
	)
```

It produce:
```
SELECT DISTINCT LEFT(user.name, 1) AS "letter"
FROM user
ORDER BY 'letter' ASC;
```
It gets the list, but not sorted.
Any idea?

**Comment by houten11** [comment]
Replace `String("letter")` with `StringColumn("letter")`. Ordering by a string constant doesn't make sense.

**Comment by ferllings** [comment]
Sorry for the confusion, I'm only starting with this lib.
Great job so far !
