### ISSUE TITLE
Count doesn't work

### ISSUE THREAD

**Issue by Spargwy** [go-jet/jet#317]
**Describe the bug**

**Environment (please complete the following information):**
 - OS: linux and windows too
 - Database: postgres
-  Database driver: sql
 - Jet version 2.10.1

**Code snippet**
```
type Count struct {
	Count int64 `sql:"count"`
}

stmt := SELECT(COUNT(table.TableName.ID).AS("count")).
		FROM(table.TableName)

	response := repomodel.Count{}

	err := stmt.QueryContext(ctx, r.JetDB, &response)
	if err != nil {
		return 0, fmt.Errorf("select count: %w", err)
	}
```
Sql in result: ```SELECT COUNT(TableName.id) AS "count"
FROM public.TableName;```

**Expected behavior**
I expect a result greater than 0 because the table is not empty. Before the count request, all rows are received and the data is ok.

**Comment by fangorn312** [comment]
I think you should put the name of the struct in the "AS" method

```
type CountResponse struct {
	Count int64 `json:"count"`
}

stmt := SELECT(COUNT(table.TableName.ID).AS("count_response.count")).
		FROM(table.TableName)

	response := repomodel.Count{}

	err := stmt.QueryContext(ctx, r.JetDB, &response)
	if err != nil {
		return 0, fmt.Errorf("select count: %w", err)
	}
	log.Println(response.Count)
```

**Comment by Spargwy** [comment]
> I think you should put the name of the struct in the "AS" method

Yes, this is the solution but I think this is a bit implicit. So examples should be added or logic changed

**Comment by houten11** [comment]
More on scanning into custom model types can be found [here](https://github.com/go-jet/jet/wiki/Query-Result-Mapping-(QRM)#custom-model-types), also check out this [faq](https://github.com/go-jet/jet/wiki/FAQ#scan-stopped-working-after-naming-a-destination-type) as well.

**Comment by Spargwy** [comment]
Thank you
