### ISSUE TITLE
request(generator): table alias

### ISSUE THREAD

**Issue by yofriadi** [go-jet/jet#319]
I see that currently generator does not support option to alias table name but defined in the generated code here [file_templates.go](https://github.com/go-jet/jet/blob/a2eb15e5666526737bf8a84d8f244db93f562309/generator/template/file_templates.go#L27)
```go
var {{tableTemplate.InstanceName}} = new{{tableTemplate.TypeName}}("{{schemaName}}", "{{.Name}}", "")
//                                                                                                ^^ here
```

this issue created to track this feature, cmiiw.

**Comment by go-jet** [comment]
Hi @yofriadi ,

This [feature](https://github.com/go-jet/jet/pull/259) has been added to master, and it will be part of next release (in week or two). 
You can use it already, just reference jet master in you go.mod.

**Comment by yofriadi** [comment]
nice, hope it will released soon, thank you!
