### ISSUE TITLE
feature(sqlbuilder): exclude AS from RETURNING output

### ISSUE THREAD

**Issue by yofriadi** [go-jet/jet#320]
consider this query with it's alias
```sql
INSERT INTO schema.tables AS t (col_1, col_2)
VALUES ($1, $2)
RETURNING t.col_1 AS "t.col_1", t.col_2 AS "t.col_2";
```

is it possible to have this instead?
```sql
INSERT INTO schema.tables AS t (col_1, col_2)
VALUES ($1, $2)
RETURNING t.col_1, t.col_2;
```

my problem is this alias will matched against my db struct name because I use other engine for the query part.
```go
type Table struct {
    // my
	Col1 pgtype.Date      `db:"col_1"` // col_1 will matched against t.col_1
	Col1 pgtype.Time      `db:"col_2"` // col_2 will matched against t.col_2
}
```

**Comment by houten11** [comment]
Can you re-alias with just the field name?

```golang
tables.Col1.AS("col_1")
tables.Col2.AS("col_2")
```

**Comment by yofriadi** [comment]
yes, it can. but I am using convenience `MyTable.AllColumns`.

actually there is ways to fix this,
1. use the alias as prefix in db tag
2. drop alias altogether
3. use alias on each column in returning or in select
4. use other scanner
5. modify the engine for the query part

yea this is not really a problem tbh, I did all and conclude for the tradeoff, thankyou, will close this as not priority I think.
