### ISSUE TITLE
Customize Generated model struct tags

### ISSUE THREAD

**Issue by KoduIsGreat** [go-jet/jet#321]
**Is your feature request related to a problem? Please describe.**
  Its pretty annoying when I generate models and I cant customize their struct tags , specifically I'd beable to use the generated models if it had json struct tags to make the Fields follow json convention but as they cannot i have to make custom models for each one that i will need to serialize out to JSON

**Describe the solution you'd like**
I'd like something where you can just tell the generator to add json struct tags to the generated model.

**Comment by houten11** [comment]
It is possible to customize struct field tags using generator customization - https://github.com/go-jet/jet/wiki/Generator#generator-customization.
