### ISSUE TITLE
Support for SQLite FTS5?

### ISSUE THREAD

**Issue by intaek-h** [go-jet/jet#347]
Does jet support [FTS5](https://www.sqlite.org/draft/fts5.html)? 

I want to create a virtual FTS5 table for search queries. But jet doesn't seem to acknowledge it. Correct me if I'm wrong because maybe I am missing something.

```sql
CREATE VIRTUAL TABLE JobPostings_fts USING fts5 (
    title,
    short_description,
    full_description,
    address
);
```

```bash
jet -source=sqlite -dsn="./local.db" -schema=part-time-mothers -path=./.gen
Retrieving schema information...
Error trace:
 - failed to query database metadata:
 - failed to get  tables metadata:
 - failed to query column metadata:
 - failed to query 'JobPostings_fts' column metadata:
 - jet:
 - no such module:
 - fts5
```

**Comment by intaek-h** [comment]
I guess Jet generator is not working when I have that `USING fts5` query. 
I thought of using raw query for FTS statements but that's also not possible when Jet generator is failing.
Full text search is critical to my project. Please help me make the decision.

**Comment by intaek-h** [comment]
found out that this is not the problem of Jet, but me not enabling fts extension when compiling my sqlite db.
closing.

**Comment by LetrixZ** [comment]
How did you solve this?

My SQLite installation has `ENABLE_FTS5` compile option
