### ISSUE TITLE
Unsupported sql column for the array in postgres

### ISSUE THREAD

**Issue by iFurySt** [go-jet/jet#350]
**Describe the bug**
- [SQL Builder] Unsupported sql column 'roles bigint[]', using StringColumn instead.

**Environment (please complete the following information):**
 - OS: macosx
 - Database: postgres
 - Jet version: v2.11.1

**Code snippet**
```sql
CREATE TABLE IF NOT EXISTS users (
    id bigserial PRIMARY KEY,
    status boolean NOT NULL DEFAULT true,

    username varchar(255) NOT NULL,
    email varchar(255) NOT NULL,

    roles BIGINT[],

    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL
);
```

**Expected behavior**
why don't support the array in postgres?

**Comment by houten11** [comment]
Array types are among the Postgres types currently unsupported. You can use [raw expressions](https://github.com/go-jet/jet/wiki/Expressions#raw-expression) for sql builder and [customize the generator](https://github.com/go-jet/jet/wiki/Generator#generator-customization) to use your array destination type.
> why don't support the array in postgres?

No one implemented it yet.

**Comment by iFurySt** [comment]
Got it, thanks. I'll have a try.
