### ISSUE TITLE
Improving Document about SELECT clause.

### ISSUE THREAD

**Issue by Q00** [go-jet/jet#359]
**Describe the bug**
There are no descriptions about using multiple WHERE clauses in the [SELECT](https://github.com/go-jet/jet/wiki/SELECT) section. It’s common to use multiple conditions in queries, but this documentation lacks examples or explanations.

I found that using .AND in WHERE is described in the [SubQuery](https://github.com/go-jet/jet/wiki/Subquery#lateral-queries) section, but it should also be in the SELECT documentation.
<img width="808" alt="image" src="https://github.com/go-jet/jet/assets/31264094/68583120-f474-407e-aa81-39ee77afc1f6">

**Environment (please complete the following information):**
Docs 
- https://github.com/go-jet/jet/wiki/SELECT
- https://github.com/go-jet/jet/wiki/Subquery#lateral-queries

**Code snippet**
- None

**Expected behavior**
	Please consider adding descriptions and examples of using multiple conditions with AND() in the SELECT section.

Let me know if you need any more help!

**Comment by houten11** [comment]
You can find more info about expressions here: https://github.com/go-jet/jet/wiki/Expressions.
Also, SQL doesn't support multiple WHERE clauses, it has to be only one.

**Comment by Q00** [comment]
> You can find more info about expressions here: https://github.com/go-jet/jet/wiki/Expressions. Also, SQL doesn't support multiple WHERE clauses, it has to be only one.

@houten11 
Thank you for your prompt response. I understand that SQL does not support multiple WHERE clauses; rather, it uses a single WHERE clause with multiple conditions combined using AND, OR, etc. My concern is specifically about the lack of examples and explanations regarding this common usage in the SELECT documentation.

The SELECT section does not currently include examples or descriptions of how to use multiple conditions in the WHERE clause. There is an example in the Subquery section that uses AND, but it would be beneficial to have this information readily available in the SELECT documentation as well.  Users often need to construct queries with multiple conditions, and having this information in the relevant section would make it easier for them to find and understand.

cc. @go-jet

**Comment by go-jet** [comment]
Hi @Q00 ,
There are already couple of examples for multiple conditions. For instance on the main [Readme](https://github.com/go-jet/jet#lets-write-some-sql-queries-in-go) page, [faq example](https://github.com/go-jet/jet/wiki/FAQ#how-to-construct-dynamic-condition) and in [Expressions](https://github.com/go-jet/jet/wiki/Expressions). You can also search tests for [more examples](https://github.com/search?q=repo%3Ago-jet%2Fjet+path%3A%2F%5Etests%5C%2F%2F+.WHERE%28&type=code). 
Maybe we can add one more example for global AND and OR functions inside [Logical operators](https://github.com/go-jet/jet/wiki/Expressions#logical-operators). I don't think SELECT section needs to be updated. SELECT section is just to list the supported clauses.
