### ISSUE TITLE
ProjectionList{ColumnList{...}}.As("some_alias")  results in no columns being rendered in the SQL

### ISSUE THREAD

**Issue by josephbuchma** [go-jet/jet#364]
**Describe the bug**

ProjectionList.As method drops ColumnList columns.

**Environment (please complete the following information):**
 - OS: macosx
 - Database: mysql
-  Database driver: github.com/go-sql-driver/mysql 
 - Jet version v2.11.1

**Code snippet**

```go
strain := table.Strain
selects := mysql.ProjectionList{strain.AllColumns}.As("my_strain")
q := mysql.SELECT(selects).FROM(strain)
fmt.Println(q.DebugSql())
```
Output:
```
SELECT
FROM strain;
```

**Expected behavior**
I expected to see selected columns in the resulting SQL.

**Comment by josephbuchma** [comment]
Opened PR with fix.
Another thing I'd like to have is ability to use `As("")` to remove table prefixes from aliases:

```go
	selects := mysql.ProjectionList{
		strain.StrainID,
		strain.StrainName,
	}.As("")
	q := mysql.SELECT(selects).FROM(strain)
	fmt.Println(q.DebugSql())
```
Actual output:
```
SELECT strain_minimal.strain_id AS ".strain_id",
     strain_minimal.strain_name AS ".strain_name"
FROM company.strain AS strain_minimal;
```
Desired output:
```
SELECT strain_minimal.strain_id AS "strain_id",
     strain_minimal.strain_name AS "strain_name"
FROM company.strain AS strain_minimal;
```
But maybe this deserves its own method?

**Comment by go-jet** [comment]
I think we can use the same method. If empty string is passed it should be safe to remove a dot. QRM will work regardless of dot, and I don't think anyone currently uses this kind of aliasing.
