### ISSUE TITLE
Ability to add db tags to use pgx struct scanning

### ISSUE THREAD

**Issue by WilliamSoler** [go-jet/jet#366]
I am using **pgx** together with jet, and currently to be able to scan rows into structs I have to use AS method and write all the columns instead of using _AllColumns_, example:

```
	stmnt := ResidenceInformations.SELECT(ResidenceInformations.City.AS("City"),
		ResidenceInformations.Country.AS("Country"),
		ResidenceInformations.PostalCode.AS("ZipCode"),
		ResidenceInformations.Address.AS("Address"),
		ResidenceInformations.UserID.AS("UserID"),
	).
		WHERE(ResidenceInformations.UserID.EQ(String(id))).
		LIMIT(1)
	sql, args := stmnt.Sql()
	rows, err := as.db.Query(context.Background(), sql, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	residentialAddress, err := pgx.CollectOneRow(rows, pgx.RowToStructByName[model.ResidenceInformations])
```

Since to use _RowToStructByName_ **pgx** functionality the resulting SQL has to match the name of the struct field or it needs a _db_ tag to map the data into the struct.

Therefore it would be very nice to support  **db** tags to delete a lot of this code.

**Comment by houten11** [comment]
This is already supported, using generator customization - https://github.com/go-jet/jet/wiki/Generator#generator-customization.

**Comment by go-jet** [comment]
Hi @WilliamSoler, check this issue - https://github.com/go-jet/jet/issues/364. When this issues is resolved you should be able to write:

```golang
	stmnt := ResidenceInformations.SELECT(ResidenceInformations.AllColumns.As("")).
		WHERE(ResidenceInformations.UserID.EQ(String(id))).
		LIMIT(1)
```

**Comment by go-jet** [comment]
With the release v2.12.0 table aliases can now be omitted from `ColumnList` and `ProjectionList` by passing an empty string to the `As` method ([wiki](https://github.com/go-jet/jet/wiki/SQL-Builder#column-list))
