### ISSUE TITLE
View models - NOT NULL columns have pointers

### ISSUE THREAD

**Issue by diogox** [go-jet/jet#371]
**Describe the bug**
First of all, I'm not sure if this is a bug. So I'm just going to pose this as a question.

I'm generating a view on my SQLite DB. The columns are selected from tables where they are NOT NULL.

However, the generated model for the view seems to have pointers for all the fields.

Is this intended behavior? Am I doing something wrong?

Happy to provide more context, but this is probably not specific to my SQL statements 🤔

**Comment by go-jet** [comment]
Hi @diogox, sqlite(as well as postgres) does not track the nullability of the view columns, they are always marked as nullable. That is why jet generator always generates fields with a pointer.
To overcome this issue you customize the generator - https://github.com/go-jet/jet/wiki/Generator#generator-customization.

**Comment by diogox** [comment]
I see. I assumed the models were generated from the tables of origin.

Makes sense then. Thank you!
