### ISSUE TITLE
Database Name Change

### ISSUE THREAD

**Issue by aunjaffery** [go-jet/jet#372]
I developed the backend with dev Database, and all the imports through out the app looks like this
`pet_store/.gen/petdatabase/model`
`pet_store/.gen/petdatabase/table`
but the production database has different name. (database schema is exactly the same)
do i have to change all my imports now?
does the db name have to be same?
can't I use a generic(placeholder) name?

 - OS: linux
 - Database: mysql
-  Database driver: go-sql-driver/mysql
 - Jet version: v2.11.0

**Comment by houten11** [comment]
You can call `UseSchema("productiondbname")` at the start of your program - https://github.com/go-jet/jet/wiki/FAQ#how-to-use-jet-in-multi-tenant-environment.

**Comment by aunjaffery** [comment]
I'm sorry for being a noob. But do I keep my ".gen" folder generated from dev_db. or should i generate a new ".gen" from Prod_db(name is different) for deploying?

**Comment by houten11** [comment]
Everything remains the same, only at the server startup you call `UseSchema("productiondbname")` for the production environment.

**Comment by aunjaffery** [comment]
Ok thanks!
