### ISSUE TITLE
Unset = nil

### ISSUE THREAD

**Issue by DevX86** [go-jet/jet#403]
When using the 
```go
INSERT().MODEL()
````

Assuming id is a uuid, if we want to exclude the ID to have the database autogenerate it, we currently do.
```go
INSERT(table.Xyz.AllColumn.
    Exclude(table.Xyz.ID).
MODEL()
````
Which is cool that we have this functionality!

A problem I have run into recently is when writing integration tests, we need to seed an ID into the database. If we remove the exclude it works, however when preforming the normal statements, the id is `uuid.Nil` and it will insert `00000000-0000-0000-0000-000000000000` into the database instead of letting it generate one. Is there a way to fix this seamlessly so that it treats `uuid.Nil` as nil/null ? I was going to write a helper function like this but it's a bit ugly.

```go
INSERT(table.Xyz.AllColumn.
    Exclude(utils.NullUUID(id, table.Xyz.ID)).
MODEL()
````

Which would be a utility function that returns the input field (not sure if this would work in practice) if the id field if is `uuid.Nil`, or return nil (as in exclude nothing) if the id field was present. 

Is there a way we can toggle some sort of default functionality todo this? (ideally with time.Time also for something like created_at, currently an empty time.Time{} will just set to the beginning of time into the database instead of nil as well)

**Comment by DevX86** [comment]
Would it be something like

```go
func UnwindRowFromModel(columns []Column, data interface{}) []Serializer {
	structValue := reflect.Indirect(reflect.ValueOf(data))

	row := []Serializer{}

	utils.ValueMustBe(structValue, reflect.Struct, "jet: data has to be a struct")

	for _, column := range columns {
		columnName := column.Name()
		structFieldName := utils.ToGoIdentifier(columnName)

		structField := structValue.FieldByName(structFieldName)

		if !structField.IsValid() {
			panic("missing struct field for column : " + columnName)
		}

		var field interface{}

		if structField.Kind() == reflect.Ptr && structField.IsNil() || uuid.Nil || time.Time{} {
			field = nil
		} else {
			field = reflect.Indirect(structField).Interface()
		}

		row = append(row, literal(field))
	}

	return row
}

```

**Comment by houten11** [comment]
Why would you have different behavior for your production and tests? What are tests even testing then?

**Comment by DevX86** [comment]
> Why would you have different behavior for your production and tests? What are tests even testing then?

Seeding the database within the test using the repository layer's create rather than raw sql. 
Testing the controller for the actual test.

**Comment by houten11** [comment]
I don't understand, what stops you from getting a generated UUID from the insert query using `RETURNING`(or in the case of `mysql` with a new select query).

**Comment by DevX86** [comment]
> I don't understand, what stops you from getting a generated UUID from the insert query using `RETURNING`(or in the case of `mysql` with a new select query).

On the insert in order for it to generate a uuid you have to not specify it. If you specify it with the current go-jet setup it'll set the id to `00000000-0000-0000-0000-000000000000` which is a nil id. The database will accept it instead of generating one as it is a valid uuid.

**Comment by DevX86** [comment]
> > I don't understand, what stops you from getting a generated UUID from the insert query using `RETURNING`(or in the case of `mysql` with a new select query).
> 
> On the insert in order for it to generate a uuid you have to not specify it. If you specify it with the current go-jet setup it'll set the id to `00000000-0000-0000-0000-000000000000` which is a nil id. The database will accept it instead of generating one as it is a valid uuid.

Also because of this anywhere I have an insert I have to use `Except(table.Xyz.ID, table.Xyz.CreatedAt)` when using `MODEL()`.

**Comment by DevX86** [comment]
Note: Using postgres.

**Comment by houten11** [comment]
I understand your feature request. I don't understand why it is needed. Why is there a different behavior in production and testing? Why do tests generate UUIDs on the server and production generates UUIDs on the database?

**Comment by DevX86** [comment]
> I understand your feature request. I don't understand why it is needed. Why is there a different behavior in production and testing? Why do tests generate UUIDs on the server and production generates UUIDs on the database?

I believe the database should generate such things, it's why there are defaults, especially for things like created at, it should be record insertion time not the application processing time.

The tests need to establish ids to generate relationships between entities.

**Comment by houten11** [comment]
> I believe the database should generate such things, it's why there are defaults, especially for things like created at, it should be record insertion time not the application processing time.

Agree.

> The tests need to establish ids to generate relationships between entities.

Disagree. Tests should establish ID relationships between entities the same way your server does. Otherwise, they are not testing the server.

**Comment by DevX86** [comment]
> > I believe the database should generate such things, it's why there are defaults, especially for things like created at, it should be record insertion time not the application processing time.
> 
> Agree.
> 
> > The tests need to establish ids to generate relationships between entities.
> 
> Disagree. Tests should establish ID relationships between entities the same way your server does. Otherwise, they are not testing the server.

It's for seeding the server not testing application logic.

**Comment by safaci2000** [comment]
Why don't you use the same tools you use for managing the DB state and schema management? In my case I use dbmate to manage the DDL and DML updates.  So loading the data I simply rely on the tool I'm suing.

This is part of 'bootstrap' for testcontainers.  The test spins up a container, patches up the DATABASE_URL ENV and I run the migration to get into the same state as production.

Any 'Writes' I need to do, I use the production logic to create the entities and delete them.  If you have a valid CRUD you should use the prod code to generate all the entities for your tests IMO.

```go
	dbURI := os.Getenv("DATABASE_URL")

	u, err := url.Parse(dbURI)
	assert.Nil(t, err)

	db := dbmate.New(u)
	err = db.CreateAndMigrate()
	if err != nil {
		slog.Error("Unable to apply database migration")
		cancel()
	}
```
