### ISSUE TITLE
Schema rename support

### ISSUE THREAD

**Issue by joonash** [go-jet/jet#46]
Add support for renaming the schema for generated code. Currently there is no way to use the generated code for identical database structure using two different schema names. 

Use cases for this includes multitenant systems and/or using different schema name in test database than in development in order to avoid date-destroying accidents in production database. The issues is even more serious in MySQL, as the schema name is in fact the name of the database.

Furthermore, it would be nice to have support for using the default schema (i.e. leave out the schema name part in the SQL queries) for the above use cases.

Support can be build just like the `AS` -function is supported in the generated code. This allows the same generated code to access tables in multiple schemas even simultaneously.

**Comment by go-jet** [comment]
Agreed, it make sense to have ability to set a new schema name.

**Comment by go-jet** [comment]
Schema rename support is now included in the latests v2.5.0 release.
