### ISSUE TITLE
Dynamically construct ORDER BY

### ISSUE THREAD

**Issue by gkdr** [go-jet/jet#48]
Hi, I have a question.

Based on a selection of fields, I am dynamically joining tables by conditionally calling `LEFT_JOIN` and appending the joined table's columns to a `[]mysql.Projection` which I use in the final `SELECT()`. This works pretty well.

Now I want to dynamically construct the `ORDER_BY()` based on the columns I joined, but I fail to see how. The function takes arguments of the internal type `jet.OrderByClause`, and I have not found an exported type (or interface) I can use to have a slice of these I can append to.

Did I miss something, or is there currently no way to do this? I would really prefer to avoid using subselects in the joined tables just for the ordering.

Thanks in advance!

**Comment by go-jet** [comment]
Those types are not exposed currently, but they should be.
Feel free to open MR, if you have some time.

**Comment by gkdr** [comment]
Thanks for the reply. That's what I suspected, and I'll try it soon.
