### ISSUE TITLE
Pgx compatible? 

### ISSUE THREAD

**Issue by jamesthegiantpeach** [go-jet/jet#59]
Hi thanks for this repo.

It seems like the query interface is meant for libpq driver. Any chance this is compatible with pgx?

**Comment by go-jet** [comment]
Statement query methods can be used with any driver, as long as driver implements standard `*sql.DB` interface - https://github.com/go-jet/jet/blob/master/qrm/db.go.
Main `pgx` Conn does not implement this interface so it is not possible to use it. 
But, as I can see `pgx` also has `stdlib` package, which implements standard DB interface, and `DB` and `Tx` from this package you should be able to use with `jet`.
https://github.com/jackc/pgx/tree/master/stdlib

**Comment by jamesthegiantpeach** [comment]
Thank you!
