### ISSUE TITLE
IN doesn't accept []StringExpression...

### ISSUE THREAD

**Issue by Sytten** [go-jet/jet#60]
Hi there!
Awesome job, I really like the lib for far :)
So I have this particular query:
```golang
err := SELECT(Type.Name.AS("parentType"), Field.AllColumns).
		FROM(Field).
		FROM(Field.INNER_JOIN(Type, Type.ID.EQ(Field.ParentTypeID))).
		WHERE(Field.ParentTypeID.IN(types...)).
		Query(s.db, &existingFields)
```
Where types is `[]StringExpression`. 
I would have expected it to be accepted but it gives me an error:
```
Cannot use 't' (type []StringExpression) as type []Expression 
```
No sure what is wrong. I am using Postgres.

**Comment by Sytten** [comment]
For now I casted the elements of the array to `Expression`, but it would be nice if it worked. I looks like a bug in the variadic not understanding that a `StringExpression` is an `Expression`.

**Comment by go-jet** [comment]
Hi Sytten. 
Unfortunately in Go it is not possible to assign array of one types into another, even if the type is extension of the other.
In this case `[]StringExpression` is not assignable to `[]Expression`, but `StringExpression` is assignable to `Expression`.
Using `types` from your example, this will not work:
`types := []StringExpression{String("type1"), String("type2")}`,
but this will:
`types := []Expression{String("type1"), String("type2")}`,
