### ISSUE TITLE
Bytea postgreql helper should accept a slice of bytes

### ISSUE THREAD

**Issue by Sytten** [go-jet/jet#63]
Currently it accepts a `string` which is a bit counter intuitive considering the model is also using `[]byte`.
This leads to more verbose input code: `Bytea(string(myHash[:])))`.
Thanks!

**Comment by go-jet** [comment]
Yeah, I agree. Unfortunately Bytea function is part of public API, so we can't update it until next major version is released.
For now, we could add a new function, for example `ByteaB` that will accept byte array.

**Comment by Sytten** [comment]
Actually the current implementation just doesn't work. If I insert data in a Bytea column with a slice, I have no way to do a comparison on it.

**Comment by go-jet** [comment]
@Sytten Could you share you example?

**Comment by Sytten** [comment]
Here is an example:
```golang

hash := sha256.Sum256([]byte("somekey"))

// Store
_, _ = ReportingKey.INSERT(ReportingKey.Hash, ReportingKey.Name).
	VALUES(hash[:], input.Name).
	RETURNING(ReportingKey.AllColumns).
	Exec(db)

// Compare
stmt := SELECT(
		ReportingKey.AllColumns,
	).FROM(
		ReportingKey,
	).WHERE(
		ReportingKey.Hash.EQ(Bytea(string(myHash[:]))),
	)

// Query
var dest []model.ReportingKey
_ = stmt.Query(s.db, &dest)

// dest is empty here
```

I also try the `hex.EncodeToString` without any success because it misses the `\x` in the written string.

**Comment by go-jet** [comment]
Aha, I see.

**Comment by go-jet** [comment]
Bytea constructor now accepts byte array as well as string in the [latests v2.5.0 release](https://github.com/go-jet/jet/releases/tag/v2.5.0).
