### ISSUE TITLE
Add raw helper with parameters

### ISSUE THREAD

**Issue by Sytten** [go-jet/jet#65]
Currently the `Raw()` function takes a string, but sometimes functions require parameters from the user. Currently you have to sanitize yourself the input and use a `fmt.Sprintf` which is prone to SQL injections.
It would be nice if we could something like: `Raw("my_function($1)", String("test"))`.

**Comment by go-jet** [comment]
Is the `my_function` a custom function or it is currently unsupported SQL function?
If it is a custom function, you can use `Func`. For instance:
```Func("my_function", String("test"), Int(11))```
If it is currently unsupported SQL function, above `Func` can also be used, or we could add support for the missing function. 
_Func support is added to `develop` branch_ https://github.com/go-jet/jet/pull/55

**Comment by Sytten** [comment]
Ho, Func would be ok for my use case.
Maybe a release would be good? Lets also add an example to the doc.
