### ISSUE TITLE
Allow multiple columns to be used in where expression

### ISSUE THREAD

**Issue by Sytten** [go-jet/jet#66]
Not sure if it is currently possible to write something like:
```
WHERE (problem_id, option) IN ((4509, 'B'), (622, 'C'), (1066, 'D'), (4059, 'A'), (4740, 'A')...)
```

**Comment by go-jet** [comment]
There is a `ROW` operator for this kind of expressions. For instance:

```go
SELECT(Actor.AllColumns).
FROM(Actor).
WHERE(
    ROW(Actor.ActorID, Actor.FirstName).IN(
                ROW(Int(1), String("Joe")),
                ROW(Int(2), String("Nick")),
            ),
)
```

**Comment by Sytten** [comment]
Great I will close my wrap PR then, not sure if that was documented in the wiki.

**Comment by go-jet** [comment]
Wiki section added - https://github.com/go-jet/jet/wiki/Expressions#row-expression.
