### ISSUE TITLE
Add values functions

### ISSUE THREAD

**Issue by Sytten** [go-jet/jet#69]
I was trying to do something similar to https://stackoverflow.com/questions/34708509/how-to-use-returning-with-on-conflict-in-postgresql/42217872#42217872
```sql
WITH input_rows(usr, contact, name) AS (
   VALUES
      (text 'foo1', text 'bar1', text 'bob1')  -- type casts in first row
    , ('foo2', 'bar2', 'bob2')
    -- more?
   )
```
But I don't think there is a VALUES function.

**Comment by Sytten** [comment]
Looking at it, the WRAP function will be needed for that https://github.com/go-jet/jet/pull/67

**Comment by go-jet** [comment]
Yeah, VALUES statement is not implemented yet. 
SELECT can be used for one row and SELECT with UNION ALL can be used for multiple rows. For instance:

```go
input_rows := CTE("input_rows")

stmt := WITH(
	input_rows.AS(
		UNION_ALL(
                        // first row columns has to be aliased
			SELECT(String("foo1").AS("foo"), String("bar1").AS("bar"), String("bob1").AS("bob")),
			SELECT(String("foo2"), String("bar2"), String("bob2")),
		),
	),
)(
	SELECT(input_rows.AllColumns()).
		FROM(input_rows),
)
```

**Comment by venimaster** [comment]
Can you use some public interface in UNION_ALL instead of private jet.SerializerStatement?
When I want to update several rows I have to write something like:
```
selects := make([]postgres.SelectStatement, 0, len(events))
for _, event := range events {
  // selects filling
}    
var eventsToUpdateTable postgres.SelectTable
if len(selects) == 1 {
  eventsToInsertTable = selects[0].AsTable("events_to_insert")
} else {
  set := postgres.UNION_ALL(selects[0], selects[1])
  for i := 2; i < len(selects); i++ {
    set = postgres.UNION_ALL(set, selects[i])
  }    
  eventsToInsertTable = set.AsTable("events_to_insert")
}
```
and I got something like `union all (... union all(... union all(...)))`
It would be nice to write at least:
```
selects := make([]postgres.SelectStatement, 0, len(events))
for _, event := range events {
  // selects filling
}
if len(selects) == 1 {
  eventsToInsertTable = selects[0].AsTable("events_to_insert")
} else if len(selects) == 2 {
  set := postgres.UNION_ALL(selects[0], selects[1])
  eventsToInsertTable = set.AsTable("events_to_insert")
} else {
  set := postgres.UNION_ALL(selects[0], selects[1], selects[2:]...)
  eventsToInsertTable = set.AsTable("events_to_insert")
}
```
but golang fails to use postgres.SelectStatement slice as slice of private jet.SerializerStatement

**Comment by houten11** [comment]
Can you do it something like this - https://github.com/go-jet/jet/discussions/301#discussioncomment-7911048?

**Comment by houten11** [comment]
There is a possibility of a small performance penalty for the huge number of rows, but the result should be the same.

**Comment by venimaster** [comment]
So why not fix it and stop adding:
1. Performance penalty.
2. Code complexity.
?
