### ISSUE TITLE
Transactions ?!

### ISSUE THREAD

**Issue by DevDevious** [go-jet/jet#70]
Hello and thank you for publishing this. 

I' been looking through the docs & samples and can't find any reference to **transactions**. Are **transactions** possible with **go-jet** (MySQL driver) ?

**Comment by go-jet** [comment]
Hi @DevDevious. 
Yes, transactions are possible.
`Query`, `QueryContext`, `Exec` and `ExecContext` accept `qrm.DB` interface which can be `*sql.DB`, `*sql.Tx` as well as `*sqlx.DB`, `*sqlx.Tx`, `*gorm.DB`, `*gorm.Tx`, etc....

**Comment by DevDevious** [comment]
> Hi @DevDevious.
> Yes, transactions are possible.
> `Query`, `QueryContext`, `Exec` and `ExecContext` accept `qrm.DB` interface which can be `*sql.DB`, `*sql.Tx` as well as `*sqlx.DB`, `*sqlx.Tx`, `*gorm.DB`, `*gorm.Tx`, etc....

Thank you @go-jet. Perfectly splendid!
