### ISSUE TITLE
I am confused about how to use v2

### ISSUE THREAD

**Issue by oderwat** [go-jet/jet#77]
I am coming back to an older evaluation project of mine and thought I need to update the `go.mod` file to use v2 (`github.com/go-jet/jet/v2`). I did, and I updated `jet` itself too.

The jet command shows 2.3.0 as the version number.

When I generate the table schemas (MariaDB), it will use a non-v2 import in the generated sources, though! Building the project will ask me to add the non-v2 path to go.mod. When I do, it won't compile because of incompatible structures.

I have a clean go (1.16.3) installation with no GOPATH set (`go env GOPATH` shows `~/go`). The project is a go.mod project and located at a different path.

When I don't use the v2 in the mod file, everything compiles fine (but probably not with the newest version of jet?).

When I use the v2 in the mod file, do a generate and manually add the v2 to all generated sources, it also compiles fine.

I also hat "one time" that `jet` actually generated `v2/mysql` imports, but I can't reproduce it.

It looks to me as if the jet tool does not correctly determine if the import paths have to use the v2 ending.

What am I doing wrong here?

**Comment by oderwat** [comment]
Well. It works when I set a GOTPATH env variable, create a src folder and use `cd $GOPATH/src/ && GO111MODULE=off go get -u github.com/go-jet/jet/cmd/jet`.

I think it should work without a GOPATH set and no usage of GO111MODULE . Since going 1.16, one should be able to install with `go install github.com/go-jet/jet/cmd/jet@latest.`

**Comment by go-jet** [comment]
It seems to me you had a two jet generator versions installed, v1 and v2(go.mod). Probably in `$GOPATH/bin` and `$HOME/go/bin`, and v1 version was always called. v2 generator will always add `/v2/mysql` in import path.
`go install github.com/go-jet/jet/cmd/jet@latest` should work if you are using go.16

**Comment by oderwat** [comment]
I am sure I only had one version and it still works when I use what I wrote above (without specifying v2). I wonder now, why that will create the imports with the v2 (as it should be the go-path version?).

```
$ make gen
cd `go env GOPATH` && mkdir -p src && cd src && GO111MODULE=off go get -u github.com/go-jet/jet/cmd/jet
jet -source=MariaDB -host=localhost -port=3306 -user=myadmin -password=****** -dbname=mxguru -path=./gen
Connecting to MySQL database: myadmin:@tcp(localhost:3306)/mxguru
Retrieving database information...
	FOUND 3 table(s), 0 view(s), 2 enum(s)
Destination directory: gen/mxguru
Cleaning up destination directory...
Generating table sql builder files...
Generating enum sql builder files...
Generating table model files...
Generating enum model files...
Done
$ head -15 gen/mxguru/table/logging.go
//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Logging = newLoggingTable()
```

Anyway, my problem is solved:

It works perfectly using the V2 path with the @latest install. I remember trying that but it failed. I must have done something different wrong at that point (I guess I added v2 as the last component in the path).
