### ISSUE TITLE
Postgres Citext Support

### ISSUE THREAD

**Issue by alexcres** [go-jet/jet#83]
If there is no Citext support, it would be great if jet can use string instead of Citext when generating.

**Comment by go-jet** [comment]
Currently, generator assumes all `USER-DEFINED` types are enums. It is the same issue as https://github.com/go-jet/jet/issues/72.
With the next release it will be possible to customize all aspects of generated model types.
For now, I would recommend to update model files manually or using a script.

**Comment by go-jet** [comment]
This issue should be now fixed on develop branch. USER-DEFINED types (excluding enums) will now always appear as string field in generated model types.

**Comment by alexcres** [comment]
Thanks, this is an amazing lib. Quick question, how do I write raw query? I am trying to call sql functions, use postgis geography, etc.

**Comment by go-jet** [comment]
There is no native geography support at the moment. 
Geography column is by default mapped to string field in model type. It is possible to customize this field with desired custom 
type(answered [here](https://github.com/go-jet/jet/issues/53#issuecomment-887654358)).
To write geography specific sql you can use [Raw operator](https://github.com/go-jet/jet/wiki/Expressions#raw-operator).
