### ISSUE TITLE
Allow to forbid-list tables from generation

### ISSUE THREAD

**Issue by vetcher** [go-jet/jet#90]
Sometimes, database contain tables that is not relates to domain itself and are serving as technical information. So we want it to be ignored by `jet`.
E.g. applied migrations list (https://github.com/pressly/goose creates table `goose_db_version`)

I propose to add some flag to cli, so generator would ignore tables passed to this flag.
```
$ jet -ignore="goose_db_version;locks"
```

**Comment by go-jet** [comment]
Yeah, make sense. The flag should probably be `-ignore-table`, to differentiate from views, and enums.

**Comment by FlymeDllVa** [comment]
LGTM

**Comment by go-jet** [comment]
New generator flags `-ignore-tables`, `-ignore-views` and `-ignore-enums` added in Release 2.7.0.
