### ISSUE TITLE
Unable to bulk-insert into a postgres db

### ISSUE THREAD

**Issue by masterkidan** [go-jet/jet#93]
Hello, 
I am getting the following error when trying to insert into a postgres db with go-jet. 
```	stmt := table.Profiles.INSERT(table.Profiles.AllColumns).MODELS(profiles)```

```

Severity:"ERROR"
Code:"42601"
Message:"syntax error at or near \",\""
Detail:""
Hint:""
Position:100
InternalPosition:0
InternalQuery:""
Where:""
SchemaName:""
TableName:""
ColumnName:""
DataTypeName:""
ConstraintName:""
```

stmt.DebugSql() returns
```2021/09/20 13:06:48 
INSERT INTO outreach_development.profiles (id, name, special_id, created_at, updated_at)
VALUES (1, 'Admin', 'Admin', '2021-09-20 13:06:46.222078-07:00', '2021-09-20 13:06:46.222078-07:00'),
       (2, 'Default', 'Default', '2021-09-20 13:06:46.222078-07:00', '2021-09-20 13:06:46.222078-07:00');

```
Which is valid and does execute fine on the server , so am a bit lost as to why this is failing . 

The schema for the table is something like this 
```
CREATE TABLE IF NOT EXISTS outreach_development.profiles (
	id integer NOT NULL,
	name character varying NOT NULL,
	special_id character varying,
	created_at timestamp without time zone NOT NULL,
	updated_at timestamp without time zone NOT NULL,
	CONSTRAINT profiles_pkey PRIMARY KEY((id) HASH)
);
```

**Comment by go-jet** [comment]
What driver are you using pq or pgx?
Also, I don't see `", "` in debug sql. Is there a chance that the error is from another query?

**Comment by masterkidan** [comment]
So it turns out this was a user error. I was using the models/table files that wer generated for 'mysql' against the postgres database. Closing this out as a no-repro
