### ISSUE TITLE
Insert using reserved keyword column names are not working

### ISSUE THREAD

**Issue by masterkidan** [go-jet/jet#94]
Insertion using reserved keyword column names like 'order' don't seem to work. This is because when the debug sql statment is printed out, it generates the field liek so 
``` `order` ```

However postgres requires that the fields be escaped with ``` " ``` and doesn't recogize `.

**Comment by go-jet** [comment]
Could you share your table and a query?
Are you using the latest 2.5.0 version?

**Comment by masterkidan** [comment]
Yes I am using the latest version "2.5.0" 

The table schema is as follows : 
`CREATE TABLE test.opportunity_stages (
    id integer NOT NULL,
    name character varying NOT NULL,
    color character varying,
    "order" integer NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    is_closed boolean DEFAULT false NOT NULL,
    is_won boolean DEFAULT false NOT NULL,
    creator_id integer,
    creator_type character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);
`

The query is something like INSERT INTO test.opportunity_stages(id, `order`, ....) again I am using the pgx driver here, so this might be similar to the other issue I had oppend where sql semantics are getting applied instead of postgres

**Comment by masterkidan** [comment]
So it turns out this was a user error. I was using the models/table files that wer generated for 'mysql' against the postgres database. Closing this out as a no-repro
